#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=0:10:00
#PBS -N mask_dtiinit

set -e

# create brainmask (if necessary) and unzip files
time singularity exec -e docker://brainlife/fsl:5.0.9 ./mask.sh

if [ -z ./mask/mask.nii.gz ];then
  echo "failed"
  exit 1
else
  exit 0
fi
